application:
  name: simple-example-node
  project: getting-started
  cloud_region: aws/us-west-2
  publicly_accessible: true
database:
- type: postgresql
  version: "11.5"
  name: my-db  
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /

